// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: requestservice/requestservice.proto

package jagw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeasurementsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MeasurementsRequest) Reset() {
	*x = MeasurementsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasurementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementsRequest) ProtoMessage() {}

func (x *MeasurementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementsRequest.ProtoReflect.Descriptor instead.
func (*MeasurementsRequest) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{0}
}

type MeasurementsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Measurements []*Measurement `protobuf:"bytes,1,rep,name=measurements" json:"measurements,omitempty"`
}

func (x *MeasurementsResponse) Reset() {
	*x = MeasurementsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasurementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementsResponse) ProtoMessage() {}

func (x *MeasurementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementsResponse.ProtoReflect.Descriptor instead.
func (*MeasurementsResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{1}
}

func (x *MeasurementsResponse) GetMeasurements() []*Measurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

type Measurement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                       *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	TimestampLatestMeasurement *int64  `protobuf:"varint,2,req,name=timestamp_latest_measurement,json=timestampLatestMeasurement" json:"timestamp_latest_measurement,omitempty"`
}

func (x *Measurement) Reset() {
	*x = Measurement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurement) ProtoMessage() {}

func (x *Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurement.ProtoReflect.Descriptor instead.
func (*Measurement) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{2}
}

func (x *Measurement) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Measurement) GetTimestampLatestMeasurement() int64 {
	if x != nil && x.TimestampLatestMeasurement != nil {
		return *x.TimestampLatestMeasurement
	}
	return 0
}

type MeasurementDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
}

func (x *MeasurementDetailsRequest) Reset() {
	*x = MeasurementDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasurementDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementDetailsRequest) ProtoMessage() {}

func (x *MeasurementDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementDetailsRequest.ProtoReflect.Descriptor instead.
func (*MeasurementDetailsRequest) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{3}
}

func (x *MeasurementDetailsRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type MeasurementDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimestampLatestMeasurement *int64               `protobuf:"varint,1,req,name=timestamp_latest_measurement,json=timestampLatestMeasurement" json:"timestamp_latest_measurement,omitempty"`
	Columns                    []*MeasurementColumn `protobuf:"bytes,2,rep,name=columns" json:"columns,omitempty"`
}

func (x *MeasurementDetailsResponse) Reset() {
	*x = MeasurementDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasurementDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementDetailsResponse) ProtoMessage() {}

func (x *MeasurementDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementDetailsResponse.ProtoReflect.Descriptor instead.
func (*MeasurementDetailsResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{4}
}

func (x *MeasurementDetailsResponse) GetTimestampLatestMeasurement() int64 {
	if x != nil && x.TimestampLatestMeasurement != nil {
		return *x.TimestampLatestMeasurement
	}
	return 0
}

func (x *MeasurementDetailsResponse) GetColumns() []*MeasurementColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

type MeasurementColumn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                 *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Type                 *string `protobuf:"bytes,2,req,name=type" json:"type,omitempty"`
	InfluxType           *string `protobuf:"bytes,3,req,name=influx_type,json=influxType" json:"influx_type,omitempty"`
	LastValueStringyfied *string `protobuf:"bytes,4,req,name=last_value_stringyfied,json=lastValueStringyfied" json:"last_value_stringyfied,omitempty"`
}

func (x *MeasurementColumn) Reset() {
	*x = MeasurementColumn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasurementColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementColumn) ProtoMessage() {}

func (x *MeasurementColumn) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementColumn.ProtoReflect.Descriptor instead.
func (*MeasurementColumn) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{5}
}

func (x *MeasurementColumn) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MeasurementColumn) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *MeasurementColumn) GetInfluxType() string {
	if x != nil && x.InfluxType != nil {
		return *x.InfluxType
	}
	return ""
}

func (x *MeasurementColumn) GetLastValueStringyfied() string {
	if x != nil && x.LastValueStringyfied != nil {
		return *x.LastValueStringyfied
	}
	return ""
}

type TopologyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys       []string `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Properties []string `protobuf:"bytes,2,rep,name=properties" json:"properties,omitempty"`
}

func (x *TopologyRequest) Reset() {
	*x = TopologyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyRequest) ProtoMessage() {}

func (x *TopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyRequest.ProtoReflect.Descriptor instead.
func (*TopologyRequest) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{6}
}

func (x *TopologyRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *TopologyRequest) GetProperties() []string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type LsNodeCoordinatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LsNodeKeys []string `protobuf:"bytes,1,rep,name=ls_node_keys,json=lsNodeKeys" json:"ls_node_keys,omitempty"`
}

func (x *LsNodeCoordinatesRequest) Reset() {
	*x = LsNodeCoordinatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsNodeCoordinatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsNodeCoordinatesRequest) ProtoMessage() {}

func (x *LsNodeCoordinatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsNodeCoordinatesRequest.ProtoReflect.Descriptor instead.
func (*LsNodeCoordinatesRequest) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{7}
}

func (x *LsNodeCoordinatesRequest) GetLsNodeKeys() []string {
	if x != nil {
		return x.LsNodeKeys
	}
	return nil
}

type TelemetryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorPath    *string         `protobuf:"bytes,1,req,name=sensor_path,json=sensorPath" json:"sensor_path,omitempty"`
	Properties    []string        `protobuf:"bytes,2,rep,name=properties" json:"properties,omitempty"`
	Unflatten     *bool           `protobuf:"varint,3,opt,name=Unflatten" json:"Unflatten,omitempty"`
	StringFilters []*StringFilter `protobuf:"bytes,4,rep,name=string_filters,json=stringFilters" json:"string_filters,omitempty"`
	RangeFilter   *RangeFilter    `protobuf:"bytes,5,opt,name=range_filter,json=rangeFilter" json:"range_filter,omitempty"`
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{8}
}

func (x *TelemetryRequest) GetSensorPath() string {
	if x != nil && x.SensorPath != nil {
		return *x.SensorPath
	}
	return ""
}

func (x *TelemetryRequest) GetProperties() []string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *TelemetryRequest) GetUnflatten() bool {
	if x != nil && x.Unflatten != nil {
		return *x.Unflatten
	}
	return false
}

func (x *TelemetryRequest) GetStringFilters() []*StringFilter {
	if x != nil {
		return x.StringFilters
	}
	return nil
}

func (x *TelemetryRequest) GetRangeFilter() *RangeFilter {
	if x != nil {
		return x.RangeFilter
	}
	return nil
}

type LsNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LsNodes []*LsNode `protobuf:"bytes,1,rep,name=ls_nodes,json=lsNodes" json:"ls_nodes,omitempty"`
}

func (x *LsNodeResponse) Reset() {
	*x = LsNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsNodeResponse) ProtoMessage() {}

func (x *LsNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsNodeResponse.ProtoReflect.Descriptor instead.
func (*LsNodeResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{9}
}

func (x *LsNodeResponse) GetLsNodes() []*LsNode {
	if x != nil {
		return x.LsNodes
	}
	return nil
}

type LsLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LsLinks []*LsLink `protobuf:"bytes,1,rep,name=ls_links,json=lsLinks" json:"ls_links,omitempty"`
}

func (x *LsLinkResponse) Reset() {
	*x = LsLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsLinkResponse) ProtoMessage() {}

func (x *LsLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsLinkResponse.ProtoReflect.Descriptor instead.
func (*LsLinkResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{10}
}

func (x *LsLinkResponse) GetLsLinks() []*LsLink {
	if x != nil {
		return x.LsLinks
	}
	return nil
}

type LsPrefixResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LsPrefixes []*LsPrefix `protobuf:"bytes,1,rep,name=ls_prefixes,json=lsPrefixes" json:"ls_prefixes,omitempty"`
}

func (x *LsPrefixResponse) Reset() {
	*x = LsPrefixResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsPrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsPrefixResponse) ProtoMessage() {}

func (x *LsPrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsPrefixResponse.ProtoReflect.Descriptor instead.
func (*LsPrefixResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{11}
}

func (x *LsPrefixResponse) GetLsPrefixes() []*LsPrefix {
	if x != nil {
		return x.LsPrefixes
	}
	return nil
}

type LsSrv6SidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LsSrv6Sids []*LsSrv6Sid `protobuf:"bytes,1,rep,name=ls_srv6_sids,json=lsSrv6Sids" json:"ls_srv6_sids,omitempty"`
}

func (x *LsSrv6SidResponse) Reset() {
	*x = LsSrv6SidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsSrv6SidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsSrv6SidResponse) ProtoMessage() {}

func (x *LsSrv6SidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsSrv6SidResponse.ProtoReflect.Descriptor instead.
func (*LsSrv6SidResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{12}
}

func (x *LsSrv6SidResponse) GetLsSrv6Sids() []*LsSrv6Sid {
	if x != nil {
		return x.LsSrv6Sids
	}
	return nil
}

type LsNodeEdgeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LsNodeEdges []*LsNodeEdge `protobuf:"bytes,1,rep,name=ls_node_edges,json=lsNodeEdges" json:"ls_node_edges,omitempty"`
}

func (x *LsNodeEdgeResponse) Reset() {
	*x = LsNodeEdgeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsNodeEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsNodeEdgeResponse) ProtoMessage() {}

func (x *LsNodeEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsNodeEdgeResponse.ProtoReflect.Descriptor instead.
func (*LsNodeEdgeResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{13}
}

func (x *LsNodeEdgeResponse) GetLsNodeEdges() []*LsNodeEdge {
	if x != nil {
		return x.LsNodeEdges
	}
	return nil
}

type LsNodeCoordinatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinates []*LsNodeCoordinates `protobuf:"bytes,1,rep,name=coordinates" json:"coordinates,omitempty"`
}

func (x *LsNodeCoordinatesResponse) Reset() {
	*x = LsNodeCoordinatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsNodeCoordinatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsNodeCoordinatesResponse) ProtoMessage() {}

func (x *LsNodeCoordinatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsNodeCoordinatesResponse.ProtoReflect.Descriptor instead.
func (*LsNodeCoordinatesResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{14}
}

func (x *LsNodeCoordinatesResponse) GetCoordinates() []*LsNodeCoordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type PeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer []*Peer `protobuf:"bytes,1,rep,name=peer" json:"peer,omitempty"`
}

func (x *PeerResponse) Reset() {
	*x = PeerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerResponse) ProtoMessage() {}

func (x *PeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerResponse.ProtoReflect.Descriptor instead.
func (*PeerResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{15}
}

func (x *PeerResponse) GetPeer() []*Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type TelemetryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TelemetryData []string `protobuf:"bytes,1,rep,name=telemetry_data,json=telemetryData" json:"telemetry_data,omitempty"`
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{16}
}

func (x *TelemetryResponse) GetTelemetryData() []string {
	if x != nil {
		return x.TelemetryData
	}
	return nil
}

var File_requestservice_requestservice_proto protoreflect.FileDescriptor

var file_requestservice_requestservice_proto_rawDesc = []byte{
	0x0a, 0x23, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6a, 0x61, 0x67, 0x77, 0x1a, 0x13, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x12, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x14, 0x4d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6a, 0x61, 0x67, 0x77,
	0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0c, 0x6d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x63, 0x0a, 0x0b, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x40, 0x0a,
	0x1c, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x5f, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x03, 0x52, 0x1a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x2f, 0x0a, 0x19, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x91, 0x01, 0x0a, 0x1a, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x1c, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x1a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x07, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x11, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x66, 0x6c, 0x75, 0x78, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x66, 0x6c, 0x75, 0x78, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x16, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x79, 0x66, 0x69, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x79, 0x66, 0x69, 0x65, 0x64, 0x22, 0x45, 0x0a, 0x0f, 0x54, 0x6f, 0x70,
	0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x22, 0x3c, 0x0a, 0x18, 0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c,
	0x6c, 0x73, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x6c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x22, 0xe2,
	0x01, 0x0a, 0x10, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x6e, 0x66, 0x6c, 0x61, 0x74, 0x74, 0x65,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x55, 0x6e, 0x66, 0x6c, 0x61, 0x74, 0x74,
	0x65, 0x6e, 0x12, 0x39, 0x0a, 0x0e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6a, 0x61, 0x67,
	0x77, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0d,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x34, 0x0a,
	0x0c, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0b, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x22, 0x39, 0x0a, 0x0e, 0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6c, 0x73, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c,
	0x73, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x6c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x39,
	0x0a, 0x0e, 0x4c, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x27, 0x0a, 0x08, 0x6c, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x73, 0x4c, 0x69, 0x6e, 0x6b,
	0x52, 0x07, 0x6c, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x43, 0x0a, 0x10, 0x4c, 0x73, 0x50,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a,
	0x0b, 0x6c, 0x73, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x73, 0x50, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x52, 0x0a, 0x6c, 0x73, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x22, 0x46,
	0x0a, 0x11, 0x4c, 0x73, 0x53, 0x72, 0x76, 0x36, 0x53, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x6c, 0x73, 0x5f, 0x73, 0x72, 0x76, 0x36, 0x5f, 0x73,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x61, 0x67, 0x77,
	0x2e, 0x4c, 0x73, 0x53, 0x72, 0x76, 0x36, 0x53, 0x69, 0x64, 0x52, 0x0a, 0x6c, 0x73, 0x53, 0x72,
	0x76, 0x36, 0x53, 0x69, 0x64, 0x73, 0x22, 0x4a, 0x0a, 0x12, 0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65,
	0x45, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0d,
	0x6c, 0x73, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x64, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x73, 0x4e, 0x6f, 0x64,
	0x65, 0x45, 0x64, 0x67, 0x65, 0x52, 0x0b, 0x6c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x45, 0x64, 0x67,
	0x65, 0x73, 0x22, 0x56, 0x0a, 0x19, 0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x39, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x73, 0x4e, 0x6f,
	0x64, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x0b, 0x63,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x22, 0x2e, 0x0a, 0x0c, 0x50, 0x65,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x70, 0x65,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e,
	0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x11, 0x54, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x0e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x32, 0xd9, 0x05, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x54,
	0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x73, 0x4c,
	0x69, 0x6e, 0x6b, 0x73, 0x12, 0x15, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x54, 0x6f, 0x70, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6a, 0x61,
	0x67, 0x77, 0x2e, 0x4c, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x73, 0x50, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x54, 0x6f, 0x70, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6a, 0x61,
	0x67, 0x77, 0x2e, 0x4c, 0x73, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x73, 0x53, 0x72,
	0x76, 0x36, 0x53, 0x69, 0x64, 0x73, 0x12, 0x15, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x54, 0x6f,
	0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x73, 0x53, 0x72, 0x76, 0x36, 0x53, 0x69, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c,
	0x73, 0x4e, 0x6f, 0x64, 0x65, 0x45, 0x64, 0x67, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x6a, 0x61, 0x67,
	0x77, 0x2e, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x45,
	0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x15, 0x2e, 0x6a, 0x61, 0x67, 0x77,
	0x2e, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x73, 0x4e,
	0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1e,
	0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x45, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x54, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x6a, 0x61, 0x67, 0x77, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x6a, 0x61,
	0x67, 0x77, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1f, 0x2e,
	0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6a, 0x61, 0x6c, 0x61, 0x70, 0x65, 0x6e, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6a,
	0x61, 0x67, 0x77, 0x3b, 0x6a, 0x61, 0x67, 0x77,
}

var (
	file_requestservice_requestservice_proto_rawDescOnce sync.Once
	file_requestservice_requestservice_proto_rawDescData = file_requestservice_requestservice_proto_rawDesc
)

func file_requestservice_requestservice_proto_rawDescGZIP() []byte {
	file_requestservice_requestservice_proto_rawDescOnce.Do(func() {
		file_requestservice_requestservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_requestservice_requestservice_proto_rawDescData)
	})
	return file_requestservice_requestservice_proto_rawDescData
}

var file_requestservice_requestservice_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_requestservice_requestservice_proto_goTypes = []interface{}{
	(*MeasurementsRequest)(nil),        // 0: jagw.MeasurementsRequest
	(*MeasurementsResponse)(nil),       // 1: jagw.MeasurementsResponse
	(*Measurement)(nil),                // 2: jagw.Measurement
	(*MeasurementDetailsRequest)(nil),  // 3: jagw.MeasurementDetailsRequest
	(*MeasurementDetailsResponse)(nil), // 4: jagw.MeasurementDetailsResponse
	(*MeasurementColumn)(nil),          // 5: jagw.MeasurementColumn
	(*TopologyRequest)(nil),            // 6: jagw.TopologyRequest
	(*LsNodeCoordinatesRequest)(nil),   // 7: jagw.LsNodeCoordinatesRequest
	(*TelemetryRequest)(nil),           // 8: jagw.TelemetryRequest
	(*LsNodeResponse)(nil),             // 9: jagw.LsNodeResponse
	(*LsLinkResponse)(nil),             // 10: jagw.LsLinkResponse
	(*LsPrefixResponse)(nil),           // 11: jagw.LsPrefixResponse
	(*LsSrv6SidResponse)(nil),          // 12: jagw.LsSrv6SidResponse
	(*LsNodeEdgeResponse)(nil),         // 13: jagw.LsNodeEdgeResponse
	(*LsNodeCoordinatesResponse)(nil),  // 14: jagw.LsNodeCoordinatesResponse
	(*PeerResponse)(nil),               // 15: jagw.PeerResponse
	(*TelemetryResponse)(nil),          // 16: jagw.TelemetryResponse
	(*StringFilter)(nil),               // 17: jagw.StringFilter
	(*RangeFilter)(nil),                // 18: jagw.RangeFilter
	(*LsNode)(nil),                     // 19: jagw.LsNode
	(*LsLink)(nil),                     // 20: jagw.LsLink
	(*LsPrefix)(nil),                   // 21: jagw.LsPrefix
	(*LsSrv6Sid)(nil),                  // 22: jagw.LsSrv6Sid
	(*LsNodeEdge)(nil),                 // 23: jagw.LsNodeEdge
	(*LsNodeCoordinates)(nil),          // 24: jagw.LsNodeCoordinates
	(*Peer)(nil),                       // 25: jagw.Peer
}
var file_requestservice_requestservice_proto_depIdxs = []int32{
	2,  // 0: jagw.MeasurementsResponse.measurements:type_name -> jagw.Measurement
	5,  // 1: jagw.MeasurementDetailsResponse.columns:type_name -> jagw.MeasurementColumn
	17, // 2: jagw.TelemetryRequest.string_filters:type_name -> jagw.StringFilter
	18, // 3: jagw.TelemetryRequest.range_filter:type_name -> jagw.RangeFilter
	19, // 4: jagw.LsNodeResponse.ls_nodes:type_name -> jagw.LsNode
	20, // 5: jagw.LsLinkResponse.ls_links:type_name -> jagw.LsLink
	21, // 6: jagw.LsPrefixResponse.ls_prefixes:type_name -> jagw.LsPrefix
	22, // 7: jagw.LsSrv6SidResponse.ls_srv6_sids:type_name -> jagw.LsSrv6Sid
	23, // 8: jagw.LsNodeEdgeResponse.ls_node_edges:type_name -> jagw.LsNodeEdge
	24, // 9: jagw.LsNodeCoordinatesResponse.coordinates:type_name -> jagw.LsNodeCoordinates
	25, // 10: jagw.PeerResponse.peer:type_name -> jagw.Peer
	6,  // 11: jagw.RequestService.GetLsNodes:input_type -> jagw.TopologyRequest
	6,  // 12: jagw.RequestService.GetLsLinks:input_type -> jagw.TopologyRequest
	6,  // 13: jagw.RequestService.GetLsPrefixes:input_type -> jagw.TopologyRequest
	6,  // 14: jagw.RequestService.GetLsSrv6Sids:input_type -> jagw.TopologyRequest
	6,  // 15: jagw.RequestService.GetLsNodeEdges:input_type -> jagw.TopologyRequest
	6,  // 16: jagw.RequestService.GetPeers:input_type -> jagw.TopologyRequest
	7,  // 17: jagw.RequestService.GetLsNodeCoordinates:input_type -> jagw.LsNodeCoordinatesRequest
	8,  // 18: jagw.RequestService.GetTelemetryData:input_type -> jagw.TelemetryRequest
	0,  // 19: jagw.RequestService.GetMeasurements:input_type -> jagw.MeasurementsRequest
	3,  // 20: jagw.RequestService.GetMeasurementDetails:input_type -> jagw.MeasurementDetailsRequest
	9,  // 21: jagw.RequestService.GetLsNodes:output_type -> jagw.LsNodeResponse
	10, // 22: jagw.RequestService.GetLsLinks:output_type -> jagw.LsLinkResponse
	11, // 23: jagw.RequestService.GetLsPrefixes:output_type -> jagw.LsPrefixResponse
	12, // 24: jagw.RequestService.GetLsSrv6Sids:output_type -> jagw.LsSrv6SidResponse
	13, // 25: jagw.RequestService.GetLsNodeEdges:output_type -> jagw.LsNodeEdgeResponse
	15, // 26: jagw.RequestService.GetPeers:output_type -> jagw.PeerResponse
	14, // 27: jagw.RequestService.GetLsNodeCoordinates:output_type -> jagw.LsNodeCoordinatesResponse
	16, // 28: jagw.RequestService.GetTelemetryData:output_type -> jagw.TelemetryResponse
	1,  // 29: jagw.RequestService.GetMeasurements:output_type -> jagw.MeasurementsResponse
	4,  // 30: jagw.RequestService.GetMeasurementDetails:output_type -> jagw.MeasurementDetailsResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_requestservice_requestservice_proto_init() }
func file_requestservice_requestservice_proto_init() {
	if File_requestservice_requestservice_proto != nil {
		return
	}
	file_core_topology_proto_init()
	file_core_filters_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_requestservice_requestservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasurementsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasurementsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Measurement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasurementDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasurementDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasurementColumn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopologyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsNodeCoordinatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelemetryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsPrefixResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsSrv6SidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsNodeEdgeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsNodeCoordinatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelemetryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_requestservice_requestservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_requestservice_requestservice_proto_goTypes,
		DependencyIndexes: file_requestservice_requestservice_proto_depIdxs,
		MessageInfos:      file_requestservice_requestservice_proto_msgTypes,
	}.Build()
	File_requestservice_requestservice_proto = out.File
	file_requestservice_requestservice_proto_rawDesc = nil
	file_requestservice_requestservice_proto_goTypes = nil
	file_requestservice_requestservice_proto_depIdxs = nil
}
