// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: requestservice/requestservice.proto

package jagw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopologyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys          []string `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	PropertyNames []string `protobuf:"bytes,2,rep,name=propertyNames" json:"propertyNames,omitempty"`
}

func (x *TopologyRequest) Reset() {
	*x = TopologyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyRequest) ProtoMessage() {}

func (x *TopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyRequest.ProtoReflect.Descriptor instead.
func (*TopologyRequest) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{0}
}

func (x *TopologyRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *TopologyRequest) GetPropertyNames() []string {
	if x != nil {
		return x.PropertyNames
	}
	return nil
}

type TelemetryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ipv4Addresses []string `protobuf:"bytes,1,rep,name=ipv4addresses" json:"ipv4addresses,omitempty"`
	PropertyNames []string `protobuf:"bytes,2,rep,name=propertyNames" json:"propertyNames,omitempty"`
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryRequest) GetIpv4Addresses() []string {
	if x != nil {
		return x.Ipv4Addresses
	}
	return nil
}

func (x *TelemetryRequest) GetPropertyNames() []string {
	if x != nil {
		return x.PropertyNames
	}
	return nil
}

type LSNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LsNodes []*LSNode `protobuf:"bytes,1,rep,name=lsNodes" json:"lsNodes,omitempty"`
}

func (x *LSNodeResponse) Reset() {
	*x = LSNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LSNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSNodeResponse) ProtoMessage() {}

func (x *LSNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSNodeResponse.ProtoReflect.Descriptor instead.
func (*LSNodeResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{2}
}

func (x *LSNodeResponse) GetLsNodes() []*LSNode {
	if x != nil {
		return x.LsNodes
	}
	return nil
}

type LSLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LsLinks []*LSLink `protobuf:"bytes,1,rep,name=lsLinks" json:"lsLinks,omitempty"`
}

func (x *LSLinkResponse) Reset() {
	*x = LSLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LSLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSLinkResponse) ProtoMessage() {}

func (x *LSLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSLinkResponse.ProtoReflect.Descriptor instead.
func (*LSLinkResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{3}
}

func (x *LSLinkResponse) GetLsLinks() []*LSLink {
	if x != nil {
		return x.LsLinks
	}
	return nil
}

type LSPrefixResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LsPrefixes []*LSPrefix `protobuf:"bytes,1,rep,name=lsPrefixes" json:"lsPrefixes,omitempty"`
}

func (x *LSPrefixResponse) Reset() {
	*x = LSPrefixResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LSPrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPrefixResponse) ProtoMessage() {}

func (x *LSPrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPrefixResponse.ProtoReflect.Descriptor instead.
func (*LSPrefixResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{4}
}

func (x *LSPrefixResponse) GetLsPrefixes() []*LSPrefix {
	if x != nil {
		return x.LsPrefixes
	}
	return nil
}

type LSSRv6SIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LsSRv6SIDs []*LSSRv6SID `protobuf:"bytes,1,rep,name=lsSRv6SIDs" json:"lsSRv6SIDs,omitempty"`
}

func (x *LSSRv6SIDResponse) Reset() {
	*x = LSSRv6SIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LSSRv6SIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSSRv6SIDResponse) ProtoMessage() {}

func (x *LSSRv6SIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSSRv6SIDResponse.ProtoReflect.Descriptor instead.
func (*LSSRv6SIDResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{5}
}

func (x *LSSRv6SIDResponse) GetLsSRv6SIDs() []*LSSRv6SID {
	if x != nil {
		return x.LsSRv6SIDs
	}
	return nil
}

type TelemetryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TelemetryData []*TelemetryData `protobuf:"bytes,1,rep,name=telemetryData" json:"telemetryData,omitempty"`
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{6}
}

func (x *TelemetryResponse) GetTelemetryData() []*TelemetryData {
	if x != nil {
		return x.TelemetryData
	}
	return nil
}

type TelemetryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ipv4Address             *string `protobuf:"bytes,1,req,name=ipv4address" json:"ipv4address,omitempty"`
	DataRate                *int64  `protobuf:"varint,2,opt,name=dataRate" json:"dataRate,omitempty"`
	PacketsSent             *int64  `protobuf:"varint,3,opt,name=packetsSent" json:"packetsSent,omitempty"`
	PacketsReceived         *int64  `protobuf:"varint,4,opt,name=packetsReceived" json:"packetsReceived,omitempty"`
	State                   *string `protobuf:"bytes,5,opt,name=state" json:"state,omitempty"`
	LastStateTransitionTime *int64  `protobuf:"varint,6,opt,name=lastStateTransitionTime" json:"lastStateTransitionTime,omitempty"`
}

func (x *TelemetryData) Reset() {
	*x = TelemetryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_requestservice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelemetryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData) ProtoMessage() {}

func (x *TelemetryData) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_requestservice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData.ProtoReflect.Descriptor instead.
func (*TelemetryData) Descriptor() ([]byte, []int) {
	return file_requestservice_requestservice_proto_rawDescGZIP(), []int{7}
}

func (x *TelemetryData) GetIpv4Address() string {
	if x != nil && x.Ipv4Address != nil {
		return *x.Ipv4Address
	}
	return ""
}

func (x *TelemetryData) GetDataRate() int64 {
	if x != nil && x.DataRate != nil {
		return *x.DataRate
	}
	return 0
}

func (x *TelemetryData) GetPacketsSent() int64 {
	if x != nil && x.PacketsSent != nil {
		return *x.PacketsSent
	}
	return 0
}

func (x *TelemetryData) GetPacketsReceived() int64 {
	if x != nil && x.PacketsReceived != nil {
		return *x.PacketsReceived
	}
	return 0
}

func (x *TelemetryData) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *TelemetryData) GetLastStateTransitionTime() int64 {
	if x != nil && x.LastStateTransitionTime != nil {
		return *x.LastStateTransitionTime
	}
	return 0
}

var File_requestservice_requestservice_proto protoreflect.FileDescriptor

var file_requestservice_requestservice_proto_rawDesc = []byte{
	0x0a, 0x23, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6a, 0x61, 0x67, 0x77, 0x1a, 0x13, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4b, 0x0a, 0x0f, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x5e, 0x0a,
	0x10, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x70, 0x76, 0x34, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x70, 0x76, 0x34, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x38, 0x0a,
	0x0e, 0x4c, 0x53, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x26, 0x0a, 0x07, 0x6c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x53, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x07,
	0x6c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x4c, 0x53, 0x4c, 0x69, 0x6e,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x6c, 0x73, 0x4c,
	0x69, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6a, 0x61, 0x67,
	0x77, 0x2e, 0x4c, 0x53, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x07, 0x6c, 0x73, 0x4c, 0x69, 0x6e, 0x6b,
	0x73, 0x22, 0x42, 0x0a, 0x10, 0x4c, 0x53, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x6c, 0x73, 0x50, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6a, 0x61, 0x67, 0x77,
	0x2e, 0x4c, 0x53, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x0a, 0x6c, 0x73, 0x50, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x65, 0x73, 0x22, 0x44, 0x0a, 0x11, 0x4c, 0x53, 0x53, 0x52, 0x76, 0x36, 0x53,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x6c, 0x73,
	0x53, 0x52, 0x76, 0x36, 0x53, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x53, 0x53, 0x52, 0x76, 0x36, 0x53, 0x49, 0x44, 0x52,
	0x0a, 0x6c, 0x73, 0x53, 0x52, 0x76, 0x36, 0x53, 0x49, 0x44, 0x73, 0x22, 0x4e, 0x0a, 0x11, 0x54,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x39, 0x0a, 0x0d, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x54,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0d, 0x74, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x22, 0xe9, 0x01, 0x0a, 0x0d,
	0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a,
	0x0b, 0x69, 0x70, 0x76, 0x34, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x0b, 0x69, 0x70, 0x76, 0x34, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x52, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x53, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x53, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a,
	0x0f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x38, 0x0a,
	0x17, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x17,
	0x6c, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x32, 0xd6, 0x02, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x4c, 0x53, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e,
	0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x53, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x53,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x15, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x54, 0x6f, 0x70,
	0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6a,
	0x61, 0x67, 0x77, 0x2e, 0x4c, 0x53, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x53, 0x50, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x54, 0x6f, 0x70,
	0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6a,
	0x61, 0x67, 0x77, 0x2e, 0x4c, 0x53, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x53, 0x53,
	0x52, 0x76, 0x36, 0x53, 0x49, 0x44, 0x73, 0x12, 0x15, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x54,
	0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x4c, 0x53, 0x53, 0x52, 0x76, 0x36, 0x53, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x2e,
	0x6a, 0x61, 0x67, 0x77, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6a, 0x61, 0x67, 0x77, 0x2e, 0x54, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a,
	0x61, 0x6c, 0x61, 0x70, 0x65, 0x6e, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6a, 0x61, 0x67,
	0x77, 0x3b, 0x6a, 0x61, 0x67, 0x77,
}

var (
	file_requestservice_requestservice_proto_rawDescOnce sync.Once
	file_requestservice_requestservice_proto_rawDescData = file_requestservice_requestservice_proto_rawDesc
)

func file_requestservice_requestservice_proto_rawDescGZIP() []byte {
	file_requestservice_requestservice_proto_rawDescOnce.Do(func() {
		file_requestservice_requestservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_requestservice_requestservice_proto_rawDescData)
	})
	return file_requestservice_requestservice_proto_rawDescData
}

var file_requestservice_requestservice_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_requestservice_requestservice_proto_goTypes = []interface{}{
	(*TopologyRequest)(nil),   // 0: jagw.TopologyRequest
	(*TelemetryRequest)(nil),  // 1: jagw.TelemetryRequest
	(*LSNodeResponse)(nil),    // 2: jagw.LSNodeResponse
	(*LSLinkResponse)(nil),    // 3: jagw.LSLinkResponse
	(*LSPrefixResponse)(nil),  // 4: jagw.LSPrefixResponse
	(*LSSRv6SIDResponse)(nil), // 5: jagw.LSSRv6SIDResponse
	(*TelemetryResponse)(nil), // 6: jagw.TelemetryResponse
	(*TelemetryData)(nil),     // 7: jagw.TelemetryData
	(*LSNode)(nil),            // 8: jagw.LSNode
	(*LSLink)(nil),            // 9: jagw.LSLink
	(*LSPrefix)(nil),          // 10: jagw.LSPrefix
	(*LSSRv6SID)(nil),         // 11: jagw.LSSRv6SID
}
var file_requestservice_requestservice_proto_depIdxs = []int32{
	8,  // 0: jagw.LSNodeResponse.lsNodes:type_name -> jagw.LSNode
	9,  // 1: jagw.LSLinkResponse.lsLinks:type_name -> jagw.LSLink
	10, // 2: jagw.LSPrefixResponse.lsPrefixes:type_name -> jagw.LSPrefix
	11, // 3: jagw.LSSRv6SIDResponse.lsSRv6SIDs:type_name -> jagw.LSSRv6SID
	7,  // 4: jagw.TelemetryResponse.telemetryData:type_name -> jagw.TelemetryData
	0,  // 5: jagw.RequestService.GetLSNodes:input_type -> jagw.TopologyRequest
	0,  // 6: jagw.RequestService.GetLSLinks:input_type -> jagw.TopologyRequest
	0,  // 7: jagw.RequestService.GetLSPrefixes:input_type -> jagw.TopologyRequest
	0,  // 8: jagw.RequestService.GetLSSRv6SIDs:input_type -> jagw.TopologyRequest
	1,  // 9: jagw.RequestService.GetTelemetryData:input_type -> jagw.TelemetryRequest
	2,  // 10: jagw.RequestService.GetLSNodes:output_type -> jagw.LSNodeResponse
	3,  // 11: jagw.RequestService.GetLSLinks:output_type -> jagw.LSLinkResponse
	4,  // 12: jagw.RequestService.GetLSPrefixes:output_type -> jagw.LSPrefixResponse
	5,  // 13: jagw.RequestService.GetLSSRv6SIDs:output_type -> jagw.LSSRv6SIDResponse
	6,  // 14: jagw.RequestService.GetTelemetryData:output_type -> jagw.TelemetryResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_requestservice_requestservice_proto_init() }
func file_requestservice_requestservice_proto_init() {
	if File_requestservice_requestservice_proto != nil {
		return
	}
	file_core_topology_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_requestservice_requestservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopologyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelemetryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LSNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LSLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LSPrefixResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LSSRv6SIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelemetryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_requestservice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelemetryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_requestservice_requestservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_requestservice_requestservice_proto_goTypes,
		DependencyIndexes: file_requestservice_requestservice_proto_depIdxs,
		MessageInfos:      file_requestservice_requestservice_proto_msgTypes,
	}.Build()
	File_requestservice_requestservice_proto = out.File
	file_requestservice_requestservice_proto_rawDesc = nil
	file_requestservice_requestservice_proto_goTypes = nil
	file_requestservice_requestservice_proto_depIdxs = nil
}
