name: Create Tag

on: 
  workflow_call:
    inputs:
      release_type:
        description: 'Name of the tag to create'
        type: string
        required: true
      tag_name:
        description: 'Name of the tag to create'
        type: string
        required: true
    outputs:
      protorepo_jagw_go_ref:
        description: "Ref used by other go modules to import this version"
        value: ${{ jobs.create-tag.outputs.protorepo_jagw_go_ref }}
 
jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs: 
      protorepo_jagw_go_ref: ${{ steps.go-ref.outputs.protorepo_jagw_go_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            const { TAG_NAME } = process.env
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${ TAG_NAME }`,
              sha: context.sha
            })
        env:
          TAG_NAME: "${{ inputs.tag_name }}"
      - name: Get ref for Golang
        id: go-ref
        run: |
          if [[ ${{ inputs.release_type }} == 'release' ]]; then
            echo "::set-output name=protorepo_jagw_go_ref::${{ inputs.tag_name }}"
          else
            echo "::set-output name=protorepo_jagw_go_ref::$(git rev-list -n 1 ${{ inputs.tag_name }})"
          fi
