name: Create Tag

on: 
  workflow_call:
    inputs:
      tag_name:
        description: 'Name of the tag to create'
        type: string
        required: true
    outputs:
      commit_sha:
        description: "SHA of latest commit"
        value: ${{ jobs.create-tag.outputs.commit_sha }}
 
jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs: 
      commit_sha: ${{ steps.get-sha.outputs.commit_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            const { TAG_NAME } = process.env
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${ TAG_NAME }`,
              sha: context.sha
            })
        env:
          TAG_NAME: "${{ inputs.tag_name }}"
      - name: Get SHA
        id: get-sha
        run: |
          echo "::set-output name=commit_sha::$(git rev-list -n 1 ${{ inputs.tag_name }})"
