name: JAGW Pipieline

on:
  workflow_dispatch:
    inputs:
      tag_name:   
        required: true
        type: string
      build_branch:
        description: "Build branch (dev | main)"
        required: true
        type: string
      release_or_dev:
        description: "Type (dev | release)"
        required: true
        type: string

jobs:
  call-create-tag:
    uses: jalapeno-api-gateway/protorepo-jagw-go/.github/workflows/create-tag.yml@main
  call-create-release:
    needs: call-create-tag
    if: github.event.inputs.release_or_dev == 'release'
    uses: jalapeno-api-gateway/protorepo-jagw-go/.github/workflows/create-release.yml@main
  call-trigger-remote-repo:
    needs: [call-create-tag]
    uses: jalapeno-api-gateway/protorepo-jagw-go/.github/workflows/trigger-remote-repo.yml@main
    with:
      repo_name: jagw-core
      workflow_file: jagw-pipeline.yml
      protorepo_jagw_go_ref: ${{ needs.call-create-tag.outputs.protorepo_jagw_go_ref }}
    secrets:
      pat_full_repo_access: ${{ secrets.PAT_FULL_REPO_ACCESS }}
