name: Trigger Remote Repo

on: 
  workflow_call:
    inputs:
      repo_name:
        description: "Name of the repo to trigger the workflow on"
        type: string
        required: true
      workflow_file:
        description: "Name of the workflow file to trigger"
        type: string
        required: true
      protorepo_jagw_go_ref:
        description: "Ref used by other go modules to import this version"
        type: string
        required: true
    secrets:
      pat_full_repo_access:
        description: "A GitHub token with full repo access."
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.0
        with:
          owner: jalapeno-api-gateway
          repo: ${{ inputs.repo_name }}
          github_token: ${{ secrets.pat_full_repo_access }}
          github_user: mbongard
          workflow_file_name: ${{ inputs.workflow_file }}
          ref: dev
          client_payload: '{"tag_name": "${{ github.event.inputs.tag_name }}", "build_branch": "${{ github.event.inputs.build_branch }}", "type": "${{ github.event.inputs.release_or_dev }}", "protorepo_jagw_go_ref": "${{ inputs.protorepo_jagw_go_ref }}"}'
          propagate_failure: false
          wait_workflow: false
